### ISSUE TITLE
Missing module.js

### ISSUE THREAD

**Issue by bumboomtamtam** [tensorflow/magenta-js#78] opened 2018-05-09 19:10 UTC
Hello,
seems like there still are calls to module.js in the 1.0.0 version of the package
plus core subfolders are empty, don't know if that's allright

**Comment by adarob** [comment] 2018-05-10 15:48
Can you clarify a bit more where you are seeing this? Are you talking about the npm package?

**Comment by adarob** [comment] 2018-05-14 13:27
Duplicate of #80

**Closed by adarob** 2018-05-14 13:27 UTC
