### ISSUE TITLE
Cannot find namespace 'WebMidi'.

### ISSUE THREAD

**Issue by Gaturae** [tensorflow/magenta-js#216] opened 2018-12-05 01:06 UTC
When I start my ng-project, I got a error like this
node_modules/@magenta/music/es5/core/recorder.d.ts(30,22): error TS2503: Cannot find namespace 'WebMidi'.
what`s wrong with my ng-project ,my ng-version is 6.0

**Comment by adarob** [comment] 2019-01-03 19:49
Closing this out due to lack of response. Please reopen if needed!

**Comment by N1nJaC0d3** [comment] 2019-03-07 15:01
> Hmm, why are you using the ts files directly? I think you should be using the built library, from `dist` instead

I just installed the latest magentamusic npm package for my Angular project.
I've got same error; I don't use the ts files directly. **In Angular typescript project, I cannot use magentamusic.js script javascript file because Angular needs Typescript and d.ts type file.**

Even though magentajs music core sources are written in Typescript having d.ts, the output files built doesn't look up d.ts correctly. IDK . Maybe WebMidi package hasn't been installed after installing npm @magenta/music package.  

ERROR in node_modules/@magenta/music/es5/core/player.d.ts(51,14): error TS2503: Cannot find namespace 'WebMidi'.
node_modules/@magenta/music/es5/core/player.d.ts(52,32): error TS2503: Cannot find namespace 'WebMidi'.
node_modules/@magenta/music/es5/core/recorder.d.ts(34,22): error TS2503: Cannot find namespace 'WebMidi'.
node_modules/@magenta/music/es5/core/recorder.d.ts(35,24): error TS2503: Cannot find namespace 'WebMidi'.
node_modules/@magenta/music/es5/core/recorder.d.ts(39,32): error TS2503: Cannot find namespace 'WebMidi'.

**Comment by loganstillings** [comment] 2019-04-01 18:26
I'm having the same issue and I think this should be reopened

**Comment by notwaldorf** [comment] 2019-04-01 18:42
This is a duplicate of https://github.com/tensorflow/magenta-js/issues/278, which is still open (i don't think we need 2 issues with the same content. I've already triaged that one, so going to re-close this one (but please follow  #278 for comments)

**Closed by notwaldorf** 2019-04-01 18:42 UTC
